### ISSUE TITLE
Serve String and HtmlElement content

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#12]
When creating a web interface, accept and serve literal string content and HtmlElement(s)

**Comment by charlieIT** [comment]
Proposed solution #1

Function page(...) should return a `Page` type object, while maintaining current logic for constructing a vuejs app, but excluding the creation of both <html> and <body> elements. 

These will be created at a later point --> new `html` function

Created function `html(elems::Array; kwargs... )` that takes and array of elements to be displayed and handles each element `Type` correctly.
Any display, layout or content generation logic pertaining array elements must be performed prior to invoking this function, as this function aims to act mainly as an aggregator of content and correct html generator.

This allows multiple vuejs apps in an Html response, serving literal string html or scripts, as well as serving lower-level HtmlElement(s) who are not members of a VueElement.

Also, function `page()` becomes the constructor of a Page Type. Name changes may be necessary, to better clarify it's goal.
Page Type broadens it usage by not only being useful for structuring Vuejs' applications, but also to structure different sets of complex frontend constructions.

Function page() has not yet received adaptation to handle different input `types` , each with it's separate handling logic.
----------------

**Implementation notes**

**new html function** , where `parsehtml` is do the magic of parsing and deconstructing different `types`

```julia
function html(elements::Vector; htmlattrs::Dict=Dict(), bodyattrs::Dict=Dict(), includes::Array{String}=[""])
    htmlpage=HtmlElement("html", [])
    head = HtmlElement("head", [])
    body = HtmlElement("body", [])

    length(htmlattrs)   > 0 ? merge!(htmlpage.attrs, htmlattrs)     : nothing
    length(bodyattrs)   > 0 ? merge!(body.attrs, bodyattrs)         : nothing
    length(includes)    > 0 ? push!(head.value, join(includes, "")) : nothing

    for element in elements
        (h, b) = parsehtml(element)
        push!(head.value, h)
        push!(body.value, b)
    end
    head.value = join(head.value, "");
    body.value = join(body.value, "");

    push!(htmlpage.value, htmlstring(head), htmlstring(body))
    return htmlstring(htmlpage)
end
```

```julia
function parsehtml(element)
    head = []
    body = []
    if element isa String
        push!(body, htmlstring(element))
        @show body
    elseif element isa HtmlElement
        if lowercase(element.tag) == "head"
            push!(head, htmlstring(element.value))
        else
            push!(body, htmlstring(element.value))
        end
    elseif element isa Page
        push!(head, htmlstring(element.head.value))
        push!(body, join([htmlstring(element.body), "<script>$(element.scripts)</script>"],""))
    elseif element isa Vector
        out = parsehtml.(element)
        for tuple in out
            @show first(tuple)
            push!(head, first(tuple)); push!(body, last(tuple))
        end
    end

    return (join(head,""), join(body,""))
end
```

**Comment by AntonioLoureiro** [comment]
#15 creates new page logic addressing this issue, slightly different!

**Comment by AntonioLoureiro** [comment]
String is already served in grid                 
`elseif r isa String
domvalue=HtmlElement("div",Dict(),12,r)`
