### ISSUE TITLE
VueStruct and Vuejs App

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#13]
Currently, when building a vuejs app/page, `app` name (VueStruct´s `id` field) is immutable and always "app".
Same behavior occurs with `el`, `state` and  `data` objects, example bellow:

```julia
comp=VueStruct("app",garr,data=data,binds=binds,methods=methods)
    scripts=[]
    push!(scripts,"const app_state = $(JSON.json(comp.def_data))")
    ## component script
    comp_script=[]
    push!(comp_script,"el: '#app'")
    push!(comp_script,"vuetify: new Vuetify()")
    push!(comp_script,"data: app_state")
```
Proposal is to make `el` mutable and user defined, keeping "app" as a fallback.
For a given `name` of `type String` , let's say `"mail_application"`, code above would look as follows:

```julia
$> julia page(..., id="mail_application")

function page(...., id::String="app")
(...)

comp=VueStruct(id, garr,data=data,binds=binds,methods=methods)
    scripts=[]
    stateObject = "$(id)_state"
    push!(scripts,"const $(stateObject) = $(JSON.json(comp.def_data))")
    ## component script
    comp_script=[]
    push!(comp_script,"el: '#$id'")
    push!(comp_script,"vuetify: new Vuetify()")
    push!(comp_script,"data: $(stateObject)")
```

**Comment by AntonioLoureiro** [comment]
app is the normal convention, you cannot have 2 pages inside a page, why is it necessary?

**Comment by charlieIT** [comment]
Limiting it may limit development of complex, modular UIs further down the line

**Comment by charlieIT** [comment]
Closed as not feasible

https://vuetifyjs.com/en/components/application

> In order for your application to work properly, you must wrap it in a v-app component. This component is required for ensuring proper cross-browser compatibility. Vuetify doesn't support multiple isolated Vuetify instances on a page. v-app can exist anywhere inside the body of your app, however, there should only be one and it must be the parent of ALL Vuetify components.
