### ISSUE TITLE
Set Cookies in response

### ISSUE THREAD

**Issue by AntonioLoureiro** [AntonioLoureiro/VueJS.jl#16]
Implement set cookies in page response, probably binding to app_state.

**Comment by charlieIT** [comment]
Potentially helpful, 
vanilla javascript to retrieve a cookie, by cookie name, client-side

```javascript
function getCookie(cname) {
  var name = cname + "=";
  var decodedCookie = decodeURIComponent(document.cookie);
  var ca = decodedCookie.split(';');
  for(var i = 0; i <ca.length; i++) {
    var c = ca[i];
    while (c.charAt(0) == ' ') {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
}
```

**Comment by AntonioLoureiro** [comment]
Use case:
Binding of cookies to app_state variables.

**Comment by charlieIT** [comment]
For client side state using localStorage feels more adequate (or sessionStorage if data should only persist while browser is open) when compared to creating and handling multiple cookies.
This preference (local or session storage) can be a property set by the dev when defining storage reactivity for a VueStruct or Page.
Would use `mounted` hook to read from localStorage on app initialization and `watchers` to modify storage on component(s) update.

Binding with cookies would follow similar logic, however I don't think this library should have deeper "server-side concerns" such as reading, interpreting or parsing an incoming or outgoing HTTP Request. 
Adding "Set-Cookie" possibilities to response(page...) could be accomplished by adding some `cookie jar` variable to `struct Page` and a related kwarg... to VueStruct initialization. 
Initial Set-Cookie logic bellow:

**Core/Page.jl **
```julia
mutable struct Page
    head::HtmlElement
    include_scripts::Array
    include_styles::Array
    components::Dict{String,Any}
    scripts::Vector{String}
    cookiejar::Dict{String, Any}
end
Page(head, sc, styles, comps, scripts) = return Page(head, sc, styles, comps, scripts, Dict{String, Any}())

function response(page::Page)
    response = HTTP.Response(200, htmlstring(page))
    if length(page.cookiejar) > 0
        [HTTP.Messages.appendheader(response, SubString("Set-Cookie")=>SubString("$k=$v")) for (k,v) in page.   cookiejar]
    end
    return response
end
````
**Test endpoint**
```julia
function home(req)
    return response(page(cc, cookies=Dict("luis"=>"1","RAS"=>"token")))
end
```

**Browser output**
