### ISSUE TITLE
Introduce Scope in Methods

### ISSUE THREAD

**Issue by AntonioLoureiro** [AntonioLoureiro/VueJS.jl#2]
Script is already performed in JS Closure that allows to use object context.
Use Path to modify app_state.

**Comment by charlieIT** [comment]
Current closure forces reactive function (methods, computed or watchers) to only known the special `$event` variable, which allows access to the original DOM event. Though $event is usually necessary, event handlers may require additional arguments to operate at a meaningful level.

Solution can be to inject closure around the event function, which is defined by the user or developer, thus ensuring any `event handler` has access to the `object context`.

Another solution could involve parsing the `script` string and extracting `function` it's arguments though this may prove difficult in cases where `script` does not follow a strict `var x = function(args) {} ` definition

**Comment by AntonioLoureiro** [comment]
#22 introduces scope in methods

**Comment by AntonioLoureiro** [comment]
Not necessary, used path in update events https://github.com/AntonioLoureiro/VueJS.jl/commit/813c3a519c25bcf0ea624211d764dc51f91cfc34
