### ISSUE TITLE
v-data-table | Filtering nth

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#25]
- [ ] Wait for user to finish typing before filtering and rendering search results.

- [ ] Adjusts filtering operators based on columns data types [different possible filtering options based on the data to which filter applies]

**Comment by AntonioLoureiro** [comment]
Implemented https://github.com/AntonioLoureiro/VueJS.jl/commit/9426a8cc7ba518f0a17e852dc08584cf74d23073
