### ISSUE TITLE
HtmlElement Alias

### ISSUE THREAD

**Issue by AntonioLoureiro** [AntonioLoureiro/VueJS.jl#30]
HtmlElement should have an Alias, too long to instantiate

**Comment by charlieIT** [comment]
since @el already refers to VueElement, maybe @html or @markup

**Comment by AntonioLoureiro** [comment]
implemented in https://github.com/AntonioLoureiro/VueJS.jl/commit/546f10bbb6b70c9a1ff0c49f69324ed336aa0389
