### ISSUE TITLE
v-html directive and element slots

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#44]
When using `v-html directive`, it appears that any `slot` will be ignored. Most likely a Vue and/or Vuetify issue, not a library issue.

Detected at `v-alert`, where its contents are bound to a `v-html` directive.

**Comment by charlieIT** [comment]
Solution would most likely be to use the `default slot position`. 

Working example
```julia
if !haskey(x.slots, "default")
	tmp = Dict("default"=>"{{@path@"*x.id*".content}}")
	length(x.slots) != 0 ? merge!(x.slots, tmp) : x.slots = tmp
end
```
Though it would most likely need an improved user-side syntax, to avoid users having to declare a `@path@` with their code.

**Comment by AntonioLoureiro** [comment]
It's a feature, v-html replaces the entire content of html record where is the slot template.
templates should be used when we do not instruct what is the content.
