### ISSUE TITLE
Datatable filters

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#52]
Filters do not correctly handle comprehensive search of `String` fields/values.

Example: 
Searching `AB` for equality in a column where `ABC`, `AB` and `ABD` exist, should return all 3 values, as `AB` exists in all of them. 
Current behaviour is to return only values exactly matching `AB`.
While typing, table is automatically rendering results and, in cases like the aforementioned, table will yield empty results until an exact match is found, making it difficult for users to search efficiently.

Proposals:
Either have an `occurs` operator that will search `String` columns for occurrences of the supplied `search value `
or,
Alter `==` operator's default behaviour such that when used over a column of `Strings` returns occurrence of the supplied `search`, and not only the exact matches.

**Comment by AntonioLoureiro** [comment]
Operator '==' is ok
Create 'contains' operator.

**Comment by AntonioLoureiro** [comment]
Introduced with https://github.com/AntonioLoureiro/VueJS.jl/commit/9441c8d77c5a51183db2f66dd3433440c0a6418e
