### ISSUE TITLE
Add search feature to v-select component

### ISSUE THREAD

**Issue by f-lourenco** [AntonioLoureiro/VueJS.jl#60]

**Comment by charlieIT** [comment]
Use **v-autocomplete**, already works properly with VueJS.jl library
"The autocomplete component extends v-select and adds the ability to filter items."
[Vuetify documentation](https://vuetifyjs.com/en/components/autocompletes/)

**Comment by AntonioLoureiro** [comment]
v-autocomplete is not implemented
