### ISSUE TITLE
VS | Datatables

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#72]
Any `v-data-table` with non-empty items will not work when placed inside a `VueStruct`.

In the images, `t2` is placed at page level and works as expected.

`t` is placed inside a `@vs teste` and will not display due to an error when accessing the table's `col_format` properties.

![image (2)](https://user-images.githubusercontent.com/11480189/113311522-511c6d80-9301-11eb-9eeb-89cca18792cf.png)
![image](https://user-images.githubusercontent.com/11480189/113313530-3e0a9d00-9303-11eb-81a3-8a00ab6fc3f2.png)

The reactive prop `:col_format` is correctly declared as `teste.t.col_format`

but the `v-html` directive is trying to access `t.col_format.col_X` instead of `teste.t.col_format.col_X` , which leads to a `TypeError: Cannot read property 'col_format' of undefined`

![image](https://user-images.githubusercontent.com/11480189/113312588-5ded9100-9302-11eb-8c67-e4d6f758b687.png)

`v-html` definition for `col_format` occurs @ [Update_validation_datatable.jl, lines 123 to 125](https://github.com/AntonioLoureiro/VueJS.jl/blob/master/src/Vuetify/Update_validation_datatable.jl#L123)

The `datatable` validator is oblivious to the fact the `table` may be contained in one, or more, nested structures, therefore cannot correctly define the `path` for the `col_format` properties.

**Comment by AntonioLoureiro** [comment]
closed by https://github.com/AntonioLoureiro/VueJS.jl/commit/b0df28df0ed7bfe403dab4419132f0f85c14c1e3
