### ISSUE TITLE
Templating for HtmlElements

### ISSUE THREAD

**Issue by charlieIT** [AntonioLoureiro/VueJS.jl#9]
Enrich an HtmlElement through a template, aimed at adding extra DOM, style or layout features.

Single element template should only affect display/visual properties.

Templates should be reusable by other elements.

Most likely adopt "Mustache syntax" {{ @arg }}

Resources:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

https://vuejs.org/v2/guide/syntax.html

**Comment by AntonioLoureiro** [comment]
With implemented Slots logic in https://github.com/AntonioLoureiro/VueJS.jl/commit/69116b471ad3aa29197c1d1fd975f9f0f6fe7228
no longer necessary
